use_frameworks!

platform :ios, '9.0'

target 'WLDoubleCell_Example' do
  pod 'WLDoubleCell', :path => '../'

  target 'WLDoubleCell_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
